Add files via upload
visualization commands doesn't work since we can't install ffpeg if I run it using vertex AI
 lightpytorch make this error: module 'torch.distributed' has no attribute 'is_torchelastic_launched'
I couldn't debug it yet.